import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { MainLayout } from '@/components/layout/MainLayout';
import { cn } from '@/lib/utils';
import { AppProvider } from '@/providers/app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en' suppressHydrationWarning>
    <body className={cn('antialiased', inter.className)}>
      <AppProvider>
        <MainLayout>{children}</MainLayout>
      </AppProvider>
    </body>
  </html>
);

export default RootLayout;
